title: A github:pages Blog
tagline: github:pages is great!
owner: Jason Siang ZHANG 
link: http://szhang.net
copyright: Copyright Jason Siang ZHANG 2015

pygments: true
permalink: '/:title'
markdown: rdiscount

exclude: [README.md]

