title: <img src="/static/images/szhang.png" width="100px"/>
tagline: 2B or not 2B
owner: Jason Siang ZHANG
link: http://szhang.net
copyright: '&copy;&nbsp;<a href="/Contact">Jason Siang ZHANG</a>'

highlighter: pygments
permalink: pretty
#markdown: maruku
markdown: kramdown
kramdown:
    input: GFM
#markdown: redcarpet
#redcarpet:
#    extensions: ["smart", "tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "highlight", "quote", "footnotes", "strikethrough", "with_toc_data"]

exclude: [README.md]

