title: <img src="/static/images/szhang.png" width="100px"/>
tagline: Science waits for no one!
owner: Jason Siang ZHANG
link: http://szhang.net
copyright: Copyright &copy; Jason Siang ZHANG

highlighter: pygments
permalink: '/:title'
#markdown: kramdown
#kramdown:
#    input: GFM
markdown: redcarpet
redcarpet:
    extensions: ["smart", "tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data", "underline", "highlight", "quote", "footnotes"]

exclude: [README.md]

