title: Siang ZHANG
tagline: Science waits for no one!
owner: Jason Siang ZHANG 
link: http://szhang.net
copyright: Copyright @ Jason Siang ZHANG

pygments: true
permalink: '/:title'
markdown: kramdown

exclude: [README.md]

