title: Siang ZHANG
tagline: Science waits for no one!
owner: Jason Siang ZHANG 
link: http://szhang.net
copyright: Copyright @ Jason Siang ZHANG

highlighter: pygments
permalink: '/:title'
#markdown: kramdown
#kramdown:
#    input: GFM
markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

exclude: [README.md]

